version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-efs-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1nylvgbyu9ei6"
s3_prefix = "sam-efs-app"
region = "us-east-1"
profile = "iamadmin-general"
capabilities = "CAPABILITY_IAM"
image_repositories = []
